// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: users.proto

package usersclient

import (
	"context"

	"zgw/ks/flash_sale/user/users"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddGoodRequest         = users.AddGoodRequest
	AddGoodResponse        = users.AddGoodResponse
	DelGoodRequest         = users.DelGoodRequest
	DelGoodResponse        = users.DelGoodResponse
	GoodsDetailedRequest   = users.GoodsDetailedRequest
	GoodsDetailedResponse  = users.GoodsDetailedResponse
	GoodsList              = users.GoodsList
	GoodsListRequest       = users.GoodsListRequest
	GoodsListResponse      = users.GoodsListResponse
	Image                  = users.Image
	IsHotRequest           = users.IsHotRequest
	IsHotResponse          = users.IsHotResponse
	MerchantLoginRequest   = users.MerchantLoginRequest
	MerchantLoginResponse  = users.MerchantLoginResponse
	OrderList              = users.OrderList
	OrderListRequest       = users.OrderListRequest
	OrderListResponse      = users.OrderListResponse
	PurchaseGood           = users.PurchaseGood
	PurchaseGoodRequest    = users.PurchaseGoodRequest
	PurchaseGoodResponse   = users.PurchaseGoodResponse
	SearchGoods            = users.SearchGoods
	SearchGoodsRequest     = users.SearchGoodsRequest
	SearchGoodsResponse    = users.SearchGoodsResponse
	SendSmsRequest         = users.SendSmsRequest
	SendSmsResponse        = users.SendSmsResponse
	UpStockMessageRequest  = users.UpStockMessageRequest
	UpStockMessageResponse = users.UpStockMessageResponse

	Users interface {
		MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*MerchantLoginResponse, error)
		SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error)
		AddGood(ctx context.Context, in *AddGoodRequest, opts ...grpc.CallOption) (*AddGoodResponse, error)
		DelGood(ctx context.Context, in *DelGoodRequest, opts ...grpc.CallOption) (*DelGoodResponse, error)
		IsHot(ctx context.Context, in *IsHotRequest, opts ...grpc.CallOption) (*IsHotResponse, error)
		GoodsList(ctx context.Context, in *GoodsListRequest, opts ...grpc.CallOption) (*GoodsListResponse, error)
		UpStockMessage(ctx context.Context, in *UpStockMessageRequest, opts ...grpc.CallOption) (*UpStockMessageResponse, error)
		OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
		SearchGoods(ctx context.Context, in *SearchGoodsRequest, opts ...grpc.CallOption) (*SearchGoodsResponse, error)
		GoodsDetailed(ctx context.Context, in *GoodsDetailedRequest, opts ...grpc.CallOption) (*GoodsDetailedResponse, error)
		PurchaseGood(ctx context.Context, in *PurchaseGoodRequest, opts ...grpc.CallOption) (*PurchaseGoodResponse, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*MerchantLoginResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.MerchantLogin(ctx, in, opts...)
}

func (m *defaultUsers) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.SendSms(ctx, in, opts...)
}

func (m *defaultUsers) AddGood(ctx context.Context, in *AddGoodRequest, opts ...grpc.CallOption) (*AddGoodResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.AddGood(ctx, in, opts...)
}

func (m *defaultUsers) DelGood(ctx context.Context, in *DelGoodRequest, opts ...grpc.CallOption) (*DelGoodResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.DelGood(ctx, in, opts...)
}

func (m *defaultUsers) IsHot(ctx context.Context, in *IsHotRequest, opts ...grpc.CallOption) (*IsHotResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.IsHot(ctx, in, opts...)
}

func (m *defaultUsers) GoodsList(ctx context.Context, in *GoodsListRequest, opts ...grpc.CallOption) (*GoodsListResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GoodsList(ctx, in, opts...)
}

func (m *defaultUsers) UpStockMessage(ctx context.Context, in *UpStockMessageRequest, opts ...grpc.CallOption) (*UpStockMessageResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.UpStockMessage(ctx, in, opts...)
}

func (m *defaultUsers) OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.OrderList(ctx, in, opts...)
}

func (m *defaultUsers) SearchGoods(ctx context.Context, in *SearchGoodsRequest, opts ...grpc.CallOption) (*SearchGoodsResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.SearchGoods(ctx, in, opts...)
}

func (m *defaultUsers) GoodsDetailed(ctx context.Context, in *GoodsDetailedRequest, opts ...grpc.CallOption) (*GoodsDetailedResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GoodsDetailed(ctx, in, opts...)
}

func (m *defaultUsers) PurchaseGood(ctx context.Context, in *PurchaseGoodRequest, opts ...grpc.CallOption) (*PurchaseGoodResponse, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.PurchaseGood(ctx, in, opts...)
}
