// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddGoodRequest struct {
	UserId      int64   `json:"userId"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Status      int64   `json:"status"`
	Description string  `json:"description"`
	StockId     int64   `json:"stockId"`
	Types       int64   `json:"types"`
	Images      []Image `json:"image"`
}

type DelGoodRequest struct {
	UserId  int64 `json:"userId"`
	GoodsId int64 `json:"goodsId"`
}

type GoodsDetailedRequest struct {
	GoodsId int64 `json:"goodsId"`
}

type GoodsListRequest struct {
	Page int64 `json:"page"`
	Size int64 `json:"size"`
}

type Image struct {
	Url     string `json:"url"`
	GoodsId string `json:"goodsId"`
}

type IsHotRequest struct {
	UserId  int64 `json:"userId"`
	GoodsId int64 `json:"goodsId"`
}

type MerchantLoginRequest struct {
	Mobile   string `json:"mobile"`
	Code     string `json:"code"`
	Username string `json:"username"`
	Password string `json:"password"`
	Types    int64  `json:"types"`
}

type OrderListRequest struct {
	Page    int64  `json:"page"`
	Size    int64  `json:"size"`
	OrderNo string `json:"orderNo"`
}

type Response struct {
	Data interface{} `json:"data"`
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
}

type SearchGoodsRequest struct {
	Name     string  `json:"name,optional"`     // 非必填
	Types    int64   `json:"types,optional"`    // 非必填
	MaxPrice float64 `json:"maxPrice,optional"` // 非必填
	MinPrice float64 `json:"minPrice,optional"` // 非必填
	Sales    int64   `json:"sales,optional"`    // 非必填
}

type SendSmsRequest struct {
	Mobile string `json:"mobile"`
}

type UpStockMessageRequest struct {
	StockNum int64 `json:"stockNum"`
	StockId  int64 `json:"stockId"`
	GoodsId  int64 `json:"goodsId"`
}

type UploadRequest struct {
}
