// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"zgw/ks/flash_sale/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add/good",
				Handler: AddGoodHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/del/good",
				Handler: DelGoodHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/goods/list",
				Handler: GoodsListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/is/hot",
				Handler: IsHotHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/merchant/login",
				Handler: MerchantLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orderList",
				Handler: OrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sms/send",
				Handler: SendSmsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upstock/message",
				Handler: UpStockMessageHandler(serverCtx),
			},
		},
	)
}
