// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: users.proto

package server

import (
	"context"

	"zgw/ks/flash_sale/user/internal/logic"
	"zgw/ks/flash_sale/user/internal/svc"
	"zgw/ks/flash_sale/user/users"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
	users.UnimplementedUsersServer
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) MerchantLogin(ctx context.Context, in *users.MerchantLoginRequest) (*users.MerchantLoginResponse, error) {
	l := logic.NewMerchantLoginLogic(ctx, s.svcCtx)
	return l.MerchantLogin(in)
}

func (s *UsersServer) SendSms(ctx context.Context, in *users.SendSmsRequest) (*users.SendSmsResponse, error) {
	l := logic.NewSendSmsLogic(ctx, s.svcCtx)
	return l.SendSms(in)
}

func (s *UsersServer) AddGood(ctx context.Context, in *users.AddGoodRequest) (*users.AddGoodResponse, error) {
	l := logic.NewAddGoodLogic(ctx, s.svcCtx)
	return l.AddGood(in)
}

func (s *UsersServer) DelGood(ctx context.Context, in *users.DelGoodRequest) (*users.DelGoodResponse, error) {
	l := logic.NewDelGoodLogic(ctx, s.svcCtx)
	return l.DelGood(in)
}

func (s *UsersServer) IsHot(ctx context.Context, in *users.IsHotRequest) (*users.IsHotResponse, error) {
	l := logic.NewIsHotLogic(ctx, s.svcCtx)
	return l.IsHot(in)
}

func (s *UsersServer) GoodsList(ctx context.Context, in *users.GoodsListRequest) (*users.GoodsListResponse, error) {
	l := logic.NewGoodsListLogic(ctx, s.svcCtx)
	return l.GoodsList(in)
}

func (s *UsersServer) UpStockMessage(ctx context.Context, in *users.UpStockMessageRequest) (*users.UpStockMessageResponse, error) {
	l := logic.NewUpStockMessageLogic(ctx, s.svcCtx)
	return l.UpStockMessage(in)
}

func (s *UsersServer) OrderList(ctx context.Context, in *users.OrderListRequest) (*users.OrderListResponse, error) {
	l := logic.NewOrderListLogic(ctx, s.svcCtx)
	return l.OrderList(in)
}
