// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListRequest) Reset() {
	*x = OrderListRequest{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListRequest) ProtoMessage() {}

func (x *OrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListRequest.ProtoReflect.Descriptor instead.
func (*OrderListRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *OrderListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderListRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OrderListRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type OrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderList     []*OrderList           `protobuf:"bytes,1,rep,name=orderList,proto3" json:"orderList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResponse) Reset() {
	*x = OrderListResponse{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResponse) ProtoMessage() {}

func (x *OrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResponse.ProtoReflect.Descriptor instead.
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *OrderListResponse) GetOrderList() []*OrderList {
	if x != nil {
		return x.OrderList
	}
	return nil
}

type OrderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MerchantID    int64                  `protobuf:"varint,3,opt,name=MerchantID,proto3" json:"MerchantID,omitempty"`
	TotalAmount   float32                `protobuf:"fixed32,4,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	ProductID     int64                  `protobuf:"varint,6,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	ProductName   string                 `protobuf:"bytes,7,opt,name=ProductName,proto3" json:"ProductName,omitempty"`
	ProductImage  string                 `protobuf:"bytes,8,opt,name=ProductImage,proto3" json:"ProductImage,omitempty"`
	Price         float32                `protobuf:"fixed32,9,opt,name=Price,proto3" json:"Price,omitempty"`
	Num           int64                  `protobuf:"varint,10,opt,name=Num,proto3" json:"Num,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,11,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *OrderList) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderList) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *OrderList) GetMerchantID() int64 {
	if x != nil {
		return x.MerchantID
	}
	return 0
}

func (x *OrderList) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderList) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderList) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *OrderList) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderList) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *OrderList) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderList) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *OrderList) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type UpStockMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockNum      int64                  `protobuf:"varint,1,opt,name=StockNum,proto3" json:"StockNum,omitempty"`
	StockId       int64                  `protobuf:"varint,2,opt,name=StockId,proto3" json:"StockId,omitempty"`
	GoodsId       int64                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpStockMessageRequest) Reset() {
	*x = UpStockMessageRequest{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpStockMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpStockMessageRequest) ProtoMessage() {}

func (x *UpStockMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpStockMessageRequest.ProtoReflect.Descriptor instead.
func (*UpStockMessageRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *UpStockMessageRequest) GetStockNum() int64 {
	if x != nil {
		return x.StockNum
	}
	return 0
}

func (x *UpStockMessageRequest) GetStockId() int64 {
	if x != nil {
		return x.StockId
	}
	return 0
}

func (x *UpStockMessageRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type UpStockMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpStockMessageResponse) Reset() {
	*x = UpStockMessageResponse{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpStockMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpStockMessageResponse) ProtoMessage() {}

func (x *UpStockMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpStockMessageResponse.ProtoReflect.Descriptor instead.
func (*UpStockMessageResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

func (x *UpStockMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GoodsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListRequest) Reset() {
	*x = GoodsListRequest{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListRequest) ProtoMessage() {}

func (x *GoodsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListRequest.ProtoReflect.Descriptor instead.
func (*GoodsListRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsListRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GoodsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []*GoodsList           `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListResponse) Reset() {
	*x = GoodsListResponse{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListResponse) ProtoMessage() {}

func (x *GoodsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListResponse.ProtoReflect.Descriptor instead.
func (*GoodsListResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsListResponse) GetUserList() []*GoodsList {
	if x != nil {
		return x.UserList
	}
	return nil
}

type GoodsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	StockId       int64                  `protobuf:"varint,6,opt,name=StockId,proto3" json:"StockId,omitempty"`
	Types         int64                  `protobuf:"varint,7,opt,name=Types,proto3" json:"Types,omitempty"`
	IsHot         int64                  `protobuf:"varint,8,opt,name=IsHot,proto3" json:"IsHot,omitempty"`
	Stock         int64                  `protobuf:"varint,9,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Supplier      string                 `protobuf:"bytes,10,opt,name=Supplier,proto3" json:"Supplier,omitempty"`
	StockNum      int64                  `protobuf:"varint,11,opt,name=StockNum,proto3" json:"StockNum,omitempty"`
	StockAddress  string                 `protobuf:"bytes,12,opt,name=StockAddress,proto3" json:"StockAddress,omitempty"`
	StockUnit     string                 `protobuf:"bytes,13,opt,name=StockUnit,proto3" json:"StockUnit,omitempty"`
	StockPrice    float32                `protobuf:"fixed32,14,opt,name=StockPrice,proto3" json:"StockPrice,omitempty"`
	StockStatus   int64                  `protobuf:"varint,15,opt,name=StockStatus,proto3" json:"StockStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsList) Reset() {
	*x = GoodsList{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsList) ProtoMessage() {}

func (x *GoodsList) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsList.ProtoReflect.Descriptor instead.
func (*GoodsList) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

func (x *GoodsList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GoodsList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsList) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsList) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GoodsList) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GoodsList) GetStockId() int64 {
	if x != nil {
		return x.StockId
	}
	return 0
}

func (x *GoodsList) GetTypes() int64 {
	if x != nil {
		return x.Types
	}
	return 0
}

func (x *GoodsList) GetIsHot() int64 {
	if x != nil {
		return x.IsHot
	}
	return 0
}

func (x *GoodsList) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsList) GetSupplier() string {
	if x != nil {
		return x.Supplier
	}
	return ""
}

func (x *GoodsList) GetStockNum() int64 {
	if x != nil {
		return x.StockNum
	}
	return 0
}

func (x *GoodsList) GetStockAddress() string {
	if x != nil {
		return x.StockAddress
	}
	return ""
}

func (x *GoodsList) GetStockUnit() string {
	if x != nil {
		return x.StockUnit
	}
	return ""
}

func (x *GoodsList) GetStockPrice() float32 {
	if x != nil {
		return x.StockPrice
	}
	return 0
}

func (x *GoodsList) GetStockStatus() int64 {
	if x != nil {
		return x.StockStatus
	}
	return 0
}

type IsHotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	GoodsId       int64                  `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsHotRequest) Reset() {
	*x = IsHotRequest{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHotRequest) ProtoMessage() {}

func (x *IsHotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHotRequest.ProtoReflect.Descriptor instead.
func (*IsHotRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *IsHotRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsHotRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type IsHotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsHotResponse) Reset() {
	*x = IsHotResponse{}
	mi := &file_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHotResponse) ProtoMessage() {}

func (x *IsHotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHotResponse.ProtoReflect.Descriptor instead.
func (*IsHotResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{9}
}

func (x *IsHotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DelGoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	GoodsId       int64                  `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelGoodRequest) Reset() {
	*x = DelGoodRequest{}
	mi := &file_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelGoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelGoodRequest) ProtoMessage() {}

func (x *DelGoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelGoodRequest.ProtoReflect.Descriptor instead.
func (*DelGoodRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{10}
}

func (x *DelGoodRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DelGoodRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type DelGoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelGoodResponse) Reset() {
	*x = DelGoodResponse{}
	mi := &file_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelGoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelGoodResponse) ProtoMessage() {}

func (x *DelGoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelGoodResponse.ProtoReflect.Descriptor instead.
func (*DelGoodResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{11}
}

func (x *DelGoodResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	GoodsId       string                 `protobuf:"bytes,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{12}
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

type AddGoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	StockId       int64                  `protobuf:"varint,6,opt,name=StockId,proto3" json:"StockId,omitempty"`
	Types         int64                  `protobuf:"varint,7,opt,name=Types,proto3" json:"Types,omitempty"`
	Image         []*Image               `protobuf:"bytes,8,rep,name=Image,proto3" json:"Image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodRequest) Reset() {
	*x = AddGoodRequest{}
	mi := &file_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodRequest) ProtoMessage() {}

func (x *AddGoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodRequest.ProtoReflect.Descriptor instead.
func (*AddGoodRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{13}
}

func (x *AddGoodRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddGoodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGoodRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddGoodRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddGoodRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddGoodRequest) GetStockId() int64 {
	if x != nil {
		return x.StockId
	}
	return 0
}

func (x *AddGoodRequest) GetTypes() int64 {
	if x != nil {
		return x.Types
	}
	return 0
}

func (x *AddGoodRequest) GetImage() []*Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type AddGoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodResponse) Reset() {
	*x = AddGoodResponse{}
	mi := &file_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodResponse) ProtoMessage() {}

func (x *AddGoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodResponse.ProtoReflect.Descriptor instead.
func (*AddGoodResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{14}
}

func (x *AddGoodResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_users_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{15}
}

func (x *SendSmsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type SendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResponse) Reset() {
	*x = SendSmsResponse{}
	mi := &file_users_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResponse) ProtoMessage() {}

func (x *SendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResponse.ProtoReflect.Descriptor instead.
func (*SendSmsResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{16}
}

func (x *SendSmsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MerchantLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=Code,proto3" json:"Code,omitempty"`
	Types         int64                  `protobuf:"varint,5,opt,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantLoginRequest) Reset() {
	*x = MerchantLoginRequest{}
	mi := &file_users_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantLoginRequest) ProtoMessage() {}

func (x *MerchantLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantLoginRequest.ProtoReflect.Descriptor instead.
func (*MerchantLoginRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{17}
}

func (x *MerchantLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MerchantLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MerchantLoginRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *MerchantLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MerchantLoginRequest) GetTypes() int64 {
	if x != nil {
		return x.Types
	}
	return 0
}

type MerchantLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantLoginResponse) Reset() {
	*x = MerchantLoginResponse{}
	mi := &file_users_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantLoginResponse) ProtoMessage() {}

func (x *MerchantLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantLoginResponse.ProtoReflect.Descriptor instead.
func (*MerchantLoginResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{18}
}

func (x *MerchantLoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\"T\n" +
	"\x10OrderListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x18\n" +
	"\aorderNo\x18\x03 \x01(\tR\aorderNo\"C\n" +
	"\x11OrderListResponse\x12.\n" +
	"\torderList\x18\x01 \x03(\v2\x10.users.OrderListR\torderList\"\xc3\x02\n" +
	"\tOrderList\x12\x18\n" +
	"\aOrderNo\x18\x01 \x01(\tR\aOrderNo\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x1e\n" +
	"\n" +
	"MerchantID\x18\x03 \x01(\x03R\n" +
	"MerchantID\x12 \n" +
	"\vTotalAmount\x18\x04 \x01(\x02R\vTotalAmount\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\x12\x1c\n" +
	"\tProductID\x18\x06 \x01(\x03R\tProductID\x12 \n" +
	"\vProductName\x18\a \x01(\tR\vProductName\x12\"\n" +
	"\fProductImage\x18\b \x01(\tR\fProductImage\x12\x14\n" +
	"\x05Price\x18\t \x01(\x02R\x05Price\x12\x10\n" +
	"\x03Num\x18\n" +
	" \x01(\x03R\x03Num\x12\x1e\n" +
	"\n" +
	"TotalPrice\x18\v \x01(\x02R\n" +
	"TotalPrice\"g\n" +
	"\x15UpStockMessageRequest\x12\x1a\n" +
	"\bStockNum\x18\x01 \x01(\x03R\bStockNum\x12\x18\n" +
	"\aStockId\x18\x02 \x01(\x03R\aStockId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x03R\aGoodsId\"2\n" +
	"\x16UpStockMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x10GoodsListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"A\n" +
	"\x11GoodsListResponse\x12,\n" +
	"\buserList\x18\x01 \x03(\v2\x10.users.GoodsListR\buserList\"\x9f\x03\n" +
	"\tGoodsList\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x02R\x05Price\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\x03R\x06Status\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\x18\n" +
	"\aStockId\x18\x06 \x01(\x03R\aStockId\x12\x14\n" +
	"\x05Types\x18\a \x01(\x03R\x05Types\x12\x14\n" +
	"\x05IsHot\x18\b \x01(\x03R\x05IsHot\x12\x14\n" +
	"\x05Stock\x18\t \x01(\x03R\x05Stock\x12\x1a\n" +
	"\bSupplier\x18\n" +
	" \x01(\tR\bSupplier\x12\x1a\n" +
	"\bStockNum\x18\v \x01(\x03R\bStockNum\x12\"\n" +
	"\fStockAddress\x18\f \x01(\tR\fStockAddress\x12\x1c\n" +
	"\tStockUnit\x18\r \x01(\tR\tStockUnit\x12\x1e\n" +
	"\n" +
	"StockPrice\x18\x0e \x01(\x02R\n" +
	"StockPrice\x12 \n" +
	"\vStockStatus\x18\x0f \x01(\x03R\vStockStatus\"@\n" +
	"\fIsHotRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x02 \x01(\x03R\aGoodsId\")\n" +
	"\rIsHotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x0eDelGoodRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x02 \x01(\x03R\aGoodsId\"+\n" +
	"\x0fDelGoodResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x05Image\x12\x10\n" +
	"\x03Url\x18\x01 \x01(\tR\x03Url\x12\x18\n" +
	"\aGoodsId\x18\x02 \x01(\tR\aGoodsId\"\xe0\x01\n" +
	"\x0eAddGoodRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x02R\x05Price\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\x03R\x06Status\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\x18\n" +
	"\aStockId\x18\x06 \x01(\x03R\aStockId\x12\x14\n" +
	"\x05Types\x18\a \x01(\x03R\x05Types\x12\"\n" +
	"\x05Image\x18\b \x03(\v2\f.users.ImageR\x05Image\"+\n" +
	"\x0fAddGoodResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x0eSendSmsRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"+\n" +
	"\x0fSendSmsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\x14MerchantLoginRequest\x12\x18\n" +
	"\aAccount\x18\x01 \x01(\tR\aAccount\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12\x16\n" +
	"\x06Mobile\x18\x03 \x01(\tR\x06Mobile\x12\x12\n" +
	"\x04Code\x18\x04 \x01(\tR\x04Code\x12\x14\n" +
	"\x05types\x18\x05 \x01(\x03R\x05types\"/\n" +
	"\x15MerchantLoginResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId2\x84\x04\n" +
	"\x05Users\x12J\n" +
	"\rMerchantLogin\x12\x1b.users.MerchantLoginRequest\x1a\x1c.users.MerchantLoginResponse\x128\n" +
	"\aSendSms\x12\x15.users.SendSmsRequest\x1a\x16.users.SendSmsResponse\x128\n" +
	"\aAddGood\x12\x15.users.AddGoodRequest\x1a\x16.users.AddGoodResponse\x128\n" +
	"\aDelGood\x12\x15.users.DelGoodRequest\x1a\x16.users.DelGoodResponse\x122\n" +
	"\x05IsHot\x12\x13.users.IsHotRequest\x1a\x14.users.IsHotResponse\x12>\n" +
	"\tGoodsList\x12\x17.users.GoodsListRequest\x1a\x18.users.GoodsListResponse\x12M\n" +
	"\x0eUpStockMessage\x12\x1c.users.UpStockMessageRequest\x1a\x1d.users.UpStockMessageResponse\x12>\n" +
	"\tOrderList\x12\x17.users.OrderListRequest\x1a\x18.users.OrderListResponseB\tZ\a./usersb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_users_proto_goTypes = []any{
	(*OrderListRequest)(nil),       // 0: users.OrderListRequest
	(*OrderListResponse)(nil),      // 1: users.OrderListResponse
	(*OrderList)(nil),              // 2: users.OrderList
	(*UpStockMessageRequest)(nil),  // 3: users.UpStockMessageRequest
	(*UpStockMessageResponse)(nil), // 4: users.UpStockMessageResponse
	(*GoodsListRequest)(nil),       // 5: users.GoodsListRequest
	(*GoodsListResponse)(nil),      // 6: users.GoodsListResponse
	(*GoodsList)(nil),              // 7: users.GoodsList
	(*IsHotRequest)(nil),           // 8: users.IsHotRequest
	(*IsHotResponse)(nil),          // 9: users.IsHotResponse
	(*DelGoodRequest)(nil),         // 10: users.DelGoodRequest
	(*DelGoodResponse)(nil),        // 11: users.DelGoodResponse
	(*Image)(nil),                  // 12: users.Image
	(*AddGoodRequest)(nil),         // 13: users.AddGoodRequest
	(*AddGoodResponse)(nil),        // 14: users.AddGoodResponse
	(*SendSmsRequest)(nil),         // 15: users.SendSmsRequest
	(*SendSmsResponse)(nil),        // 16: users.SendSmsResponse
	(*MerchantLoginRequest)(nil),   // 17: users.MerchantLoginRequest
	(*MerchantLoginResponse)(nil),  // 18: users.MerchantLoginResponse
}
var file_users_proto_depIdxs = []int32{
	2,  // 0: users.OrderListResponse.orderList:type_name -> users.OrderList
	7,  // 1: users.GoodsListResponse.userList:type_name -> users.GoodsList
	12, // 2: users.AddGoodRequest.Image:type_name -> users.Image
	17, // 3: users.Users.MerchantLogin:input_type -> users.MerchantLoginRequest
	15, // 4: users.Users.SendSms:input_type -> users.SendSmsRequest
	13, // 5: users.Users.AddGood:input_type -> users.AddGoodRequest
	10, // 6: users.Users.DelGood:input_type -> users.DelGoodRequest
	8,  // 7: users.Users.IsHot:input_type -> users.IsHotRequest
	5,  // 8: users.Users.GoodsList:input_type -> users.GoodsListRequest
	3,  // 9: users.Users.UpStockMessage:input_type -> users.UpStockMessageRequest
	0,  // 10: users.Users.OrderList:input_type -> users.OrderListRequest
	18, // 11: users.Users.MerchantLogin:output_type -> users.MerchantLoginResponse
	16, // 12: users.Users.SendSms:output_type -> users.SendSmsResponse
	14, // 13: users.Users.AddGood:output_type -> users.AddGoodResponse
	11, // 14: users.Users.DelGood:output_type -> users.DelGoodResponse
	9,  // 15: users.Users.IsHot:output_type -> users.IsHotResponse
	6,  // 16: users.Users.GoodsList:output_type -> users.GoodsListResponse
	4,  // 17: users.Users.UpStockMessage:output_type -> users.UpStockMessageResponse
	1,  // 18: users.Users.OrderList:output_type -> users.OrderListResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
