// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.1
// source: users.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Users_MerchantLogin_FullMethodName  = "/users.Users/MerchantLogin"
	Users_SendSms_FullMethodName        = "/users.Users/SendSms"
	Users_AddGood_FullMethodName        = "/users.Users/AddGood"
	Users_DelGood_FullMethodName        = "/users.Users/DelGood"
	Users_IsHot_FullMethodName          = "/users.Users/IsHot"
	Users_GoodsList_FullMethodName      = "/users.Users/GoodsList"
	Users_UpStockMessage_FullMethodName = "/users.Users/UpStockMessage"
	Users_OrderList_FullMethodName      = "/users.Users/OrderList"
)

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersClient interface {
	MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*MerchantLoginResponse, error)
	SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error)
	AddGood(ctx context.Context, in *AddGoodRequest, opts ...grpc.CallOption) (*AddGoodResponse, error)
	DelGood(ctx context.Context, in *DelGoodRequest, opts ...grpc.CallOption) (*DelGoodResponse, error)
	IsHot(ctx context.Context, in *IsHotRequest, opts ...grpc.CallOption) (*IsHotResponse, error)
	GoodsList(ctx context.Context, in *GoodsListRequest, opts ...grpc.CallOption) (*GoodsListResponse, error)
	UpStockMessage(ctx context.Context, in *UpStockMessageRequest, opts ...grpc.CallOption) (*UpStockMessageResponse, error)
	OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) MerchantLogin(ctx context.Context, in *MerchantLoginRequest, opts ...grpc.CallOption) (*MerchantLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantLoginResponse)
	err := c.cc.Invoke(ctx, Users_MerchantLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmsResponse)
	err := c.cc.Invoke(ctx, Users_SendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) AddGood(ctx context.Context, in *AddGoodRequest, opts ...grpc.CallOption) (*AddGoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGoodResponse)
	err := c.cc.Invoke(ctx, Users_AddGood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DelGood(ctx context.Context, in *DelGoodRequest, opts ...grpc.CallOption) (*DelGoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelGoodResponse)
	err := c.cc.Invoke(ctx, Users_DelGood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) IsHot(ctx context.Context, in *IsHotRequest, opts ...grpc.CallOption) (*IsHotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsHotResponse)
	err := c.cc.Invoke(ctx, Users_IsHot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GoodsList(ctx context.Context, in *GoodsListRequest, opts ...grpc.CallOption) (*GoodsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodsListResponse)
	err := c.cc.Invoke(ctx, Users_GoodsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpStockMessage(ctx context.Context, in *UpStockMessageRequest, opts ...grpc.CallOption) (*UpStockMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpStockMessageResponse)
	err := c.cc.Invoke(ctx, Users_UpStockMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderListResponse)
	err := c.cc.Invoke(ctx, Users_OrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
// All implementations must embed UnimplementedUsersServer
// for forward compatibility.
type UsersServer interface {
	MerchantLogin(context.Context, *MerchantLoginRequest) (*MerchantLoginResponse, error)
	SendSms(context.Context, *SendSmsRequest) (*SendSmsResponse, error)
	AddGood(context.Context, *AddGoodRequest) (*AddGoodResponse, error)
	DelGood(context.Context, *DelGoodRequest) (*DelGoodResponse, error)
	IsHot(context.Context, *IsHotRequest) (*IsHotResponse, error)
	GoodsList(context.Context, *GoodsListRequest) (*GoodsListResponse, error)
	UpStockMessage(context.Context, *UpStockMessageRequest) (*UpStockMessageResponse, error)
	OrderList(context.Context, *OrderListRequest) (*OrderListResponse, error)
	mustEmbedUnimplementedUsersServer()
}

// UnimplementedUsersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersServer struct{}

func (UnimplementedUsersServer) MerchantLogin(context.Context, *MerchantLoginRequest) (*MerchantLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MerchantLogin not implemented")
}
func (UnimplementedUsersServer) SendSms(context.Context, *SendSmsRequest) (*SendSmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedUsersServer) AddGood(context.Context, *AddGoodRequest) (*AddGoodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGood not implemented")
}
func (UnimplementedUsersServer) DelGood(context.Context, *DelGoodRequest) (*DelGoodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelGood not implemented")
}
func (UnimplementedUsersServer) IsHot(context.Context, *IsHotRequest) (*IsHotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsHot not implemented")
}
func (UnimplementedUsersServer) GoodsList(context.Context, *GoodsListRequest) (*GoodsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoodsList not implemented")
}
func (UnimplementedUsersServer) UpStockMessage(context.Context, *UpStockMessageRequest) (*UpStockMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpStockMessage not implemented")
}
func (UnimplementedUsersServer) OrderList(context.Context, *OrderListRequest) (*OrderListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OrderList not implemented")
}
func (UnimplementedUsersServer) mustEmbedUnimplementedUsersServer() {}
func (UnimplementedUsersServer) testEmbeddedByValue()               {}

// UnsafeUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServer will
// result in compilation errors.
type UnsafeUsersServer interface {
	mustEmbedUnimplementedUsersServer()
}

func RegisterUsersServer(s grpc.ServiceRegistrar, srv UsersServer) {
	// If the following call panics, it indicates UnimplementedUsersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Users_ServiceDesc, srv)
}

func _Users_MerchantLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).MerchantLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_MerchantLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).MerchantLogin(ctx, req.(*MerchantLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SendSms(ctx, req.(*SendSmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_AddGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_AddGood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddGood(ctx, req.(*AddGoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DelGood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelGoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DelGood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_DelGood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DelGood(ctx, req.(*DelGoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_IsHot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsHotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).IsHot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_IsHot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).IsHot(ctx, req.(*IsHotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GoodsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GoodsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GoodsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GoodsList(ctx, req.(*GoodsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpStockMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpStockMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpStockMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UpStockMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpStockMessage(ctx, req.(*UpStockMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_OrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).OrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_OrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).OrderList(ctx, req.(*OrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Users_ServiceDesc is the grpc.ServiceDesc for Users service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Users_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MerchantLogin",
			Handler:    _Users_MerchantLogin_Handler,
		},
		{
			MethodName: "SendSms",
			Handler:    _Users_SendSms_Handler,
		},
		{
			MethodName: "AddGood",
			Handler:    _Users_AddGood_Handler,
		},
		{
			MethodName: "DelGood",
			Handler:    _Users_DelGood_Handler,
		},
		{
			MethodName: "IsHot",
			Handler:    _Users_IsHot_Handler,
		},
		{
			MethodName: "GoodsList",
			Handler:    _Users_GoodsList_Handler,
		},
		{
			MethodName: "UpStockMessage",
			Handler:    _Users_UpStockMessage_Handler,
		},
		{
			MethodName: "OrderList",
			Handler:    _Users_OrderList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
